--- 
:backgroundrb: 
  :ip: 0.0.0.0 
  :port: 11008
  :environment: production

:schedules:
  :house_keeper_worker:
    :remove_unverified_users:
      :trigger_args: 0 */1 * * * *
    :remove_disabled_users:
      :trigger_args: 0  0  2 */1 * *
    :external_command_for_new_accounts:
      :trigger_args: 0  0  1 * * * *
    :remove_stale_sessions:
      :trigger_args: 0  0  2 * * 0 *
    :remove_stale_bdrbs:
      :trigger_args: 0  30 2 * * 0 *
    # cleanup stale radius sessions once a day
    :cleanup_stale_radius_accountings:
      :trigger_args: 0 0 0 */1 * *
    # uncomment the following lines if you do not use OpenWISP Captive Portal Manager 0.9.2
    # but you still want to be able to trace from which Access Point users connected
    # this feature depends on OpenWISP MiddleWare 0.0.7
    # OWMW must be enabled how described in the README file
    :convert_radius_accountings:
      :trigger_args: 0 */5 * * * *
