defaults: &defaults
  # registration form
  birth_date: true
  address: true
  zip: true
  city: true
  state: true
  # other stuff
  send_email_notification_to_users: true
  automatic_captive_portal_login: true
  mac_address_authentication: false
  # additional languages
  english: true
  italian: true
  spanish: true
  furlan: false
  
  # check called station id
  check_called_station_id:
    # filter radius accounting sessions older than between_min
    between_min: 10
    # filter radius accounting sessions newer than between_max
    between_max: 60

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults